<a href="https://colab.research.google.com/github/kavyakonda2003/Programs/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
dataset=pd.read_csv("/content/age_salary_dataset.csv")
dataset

     AGE   SALARY
0   20.0  20000.0
1   21.0  21000.0
2   22.0      NaN
3   23.0  23000.0
4   24.0  24000.0
5    NaN  25000.0
6   26.0  26000.0
7   27.0  27000.0
8   28.0  28000.0
9   29.0  29000.0
10  30.0  30000.0
11  31.0  31000.0

In [20]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print('independent variable (x):',X)
print('dependent variable (Y):',Y)

independent variable (x): [[20.]
 [21.]
 [22.]
 [23.]
 [24.]
 [nan]
 [26.]
 [27.]
 [28.]
 [29.]
 [30.]
 [31.]]
dependent variable (Y): [20000. 21000.    nan 23000. 24000. 25000. 26000. 27000. 28000. 29000.
 30000. 31000.]

In [21]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(missing_values=np.nan,strategy="mean")
X=imp.fit_transform(X)
Y=Y.reshape(-1,1)
Y=imp.fit_transform(Y)
Y=Y.reshape(-1)
print(X)
print(Y)

[[20.        ]
 [21.        ]
 [22.        ]
 [23.        ]
 [24.        ]
 [25.54545455]
 [26.        ]
 [27.        ]
 [28.        ]
 [29.        ]
 [30.        ]
 [31.        ]]
[20000.         21000.         25818.18181818 23000.
 24000.         25000.         26000.         27000.
 28000.         29000.         30000.         31000.        ]

In [31]:
X_df=pd.DataFrame(X,columns=dataset.columns[:-1])
Y_df=pd.DataFrame(Y,columns=[dataset.columns[-1]])
combined_data=pd.concat([X_df,Y_df],axis=1)
print("Combined data")
print(combined_data)

Combined data
          AGE        SALARY
0   20.000000  20000.000000
1   21.000000  21000.000000
2   22.000000  25818.181818
3   23.000000  23000.000000
4   24.000000  24000.000000
5   25.545455  25000.000000
6   26.000000  26000.000000
7   27.000000  27000.000000
8   28.000000  28000.000000
9   29.000000  29000.000000
10  30.000000  30000.000000
11  31.000000  31000.000000

In [32]:
combined_df=pd.DataFrame(combined_data, columns=list(dataset.columns))
combined_df.to_excel("/content/combined_data.xlsx",index=False)
print("combined DataFrame:")
print(combined_df.head())

combined DataFrame:
    AGE        SALARY
0  20.0  20000.000000
1  21.0  21000.000000
2  22.0  25818.181818
3  23.0  23000.000000
4  24.0  24000.000000